# Generated by Django 3.2.7 on 2021-10-20 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20211020_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orginal_cart',
            new_name='original_cart',
        ),
    ]
