# Generated by Django 3.2.7 on 2021-10-10 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20211009_1510'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variation',
            new_name='Sizes',
        ),
    ]
