# Generated by Django 3.2.7 on 2021-10-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20211010_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_more_images',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
