# Generated by Django 3.2.7 on 2021-10-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20211011_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colour',
            name='colour',
            field=models.CharField(choices=[('red', 'RED'), ('yellow', 'YELLOW'), ('blue', 'BLUE'), ('orange', 'ORANGE')], default='red', max_length=120),
        ),
    ]
