# Generated by Django 3.2.7 on 2021-10-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_colour_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colour',
            name='colour',
            field=models.CharField(choices=[('red', 'RED'), ('yellow', 'YELLOW'), ('blue', 'BLUE'), ('orange', 'ORANGE'), ('green', 'GREEN')], default='red', max_length=120),
        ),
    ]
