# Generated by Django 3.2.7 on 2021-10-17 12:29

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20211014_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('red', 'RED'), ('yellow', 'YELLOW'), ('blue', 'BLUE'), ('orange', 'ORANGE'), ('green', 'GREEN'), ('black', 'BLACK')], default=False, max_length=34, null=True),
        ),
    ]
